<#
.SYNOPSIS
    Builds the React WebClient and deploys to a target server's IIS.

.DESCRIPTION
    Complete pipeline:
      1. Installs Node.js dependencies (npm ci)
      2. Sets API base URL for the target environment
      3. Builds production artifacts (npm run build)
      4. Copies artifacts to the target server
      5. Configures IIS site with SPA routing

    Run from the developer machine where the WebClient source lives.

.PARAMETER SourcePath
    Path to the WebClient project root (contains package.json).
    Default: current directory.

.PARAMETER TargetServer
    Server hostname to deploy to. Default: localhost (deploy locally).

.PARAMETER WebApiUrl
    The WebApi URL the React app will call.
    Example: http://CONTROLLER01:81

.PARAMETER TargetPort
    IIS port for the WebClient site. Default: 8081

.PARAMETER TargetPath
    Deployment folder on the target server. Default: C:\inetpub\TestControllerWebClient

.PARAMETER SkipBuild
    If set, skips npm install and build. Deploys existing dist/ folder.

.EXAMPLE
    # Build and deploy to local machine
    .\Publish-WebClient.ps1 `
        -SourcePath "C:\Code\TestAgentSolution\TestController.WebClient" `
        -WebApiUrl "http://localhost:81"

.EXAMPLE
    # Build and deploy to remote controller
    .\Publish-WebClient.ps1 `
        -SourcePath "C:\Code\TestAgentSolution\TestController.WebClient" `
        -TargetServer "CONTROLLER01" `
        -WebApiUrl "http://CONTROLLER01:81" `
        -TargetPort 8081

.EXAMPLE
    # Deploy pre-built artifacts only (skip npm build)
    .\Publish-WebClient.ps1 `
        -SourcePath "C:\Code\TestAgentSolution\TestController.WebClient" `
        -TargetServer "CONTROLLER01" `
        -WebApiUrl "http://CONTROLLER01:81" `
        -SkipBuild
#>

[CmdletBinding()]
param(
    [string]$SourcePath = ".",
    [string]$TargetServer = "localhost",
    [string]$WebApiUrl = "http://localhost:81",
    [int]$TargetPort = 8081,
    [string]$TargetPath = "C:\inetpub\TestControllerWebClient",
    [switch]$SkipBuild,
    [string]$SiteName = "TestControllerWebClient",
    [string]$PoolName = "TestControllerWebClient"
)

$ErrorActionPreference = "Stop"
$startTime = Get-Date

function Log([string]$msg, [string]$lvl = "INFO") {
    $ts = (Get-Date).ToString("HH:mm:ss")
    $c = switch ($lvl) { "OK" {"Green"} "WARN" {"Yellow"} "FAIL" {"Red"} "STEP" {"Cyan"} "SKIP" {"DarkGray"} default {"White"} }
    $t = switch ($lvl) { "OK" {"[PASS]"} "FAIL" {"[FAIL]"} "WARN" {"[WARN]"} "STEP" {"[STEP]"} "SKIP" {"[SKIP]"} default {"[INFO]"} }
    Write-Host "[$ts] $t $msg" -ForegroundColor $c
}

function FailExit([string]$msg) { Log $msg "FAIL"; exit 1 }

$isLocal = ($TargetServer -eq "localhost") -or ($TargetServer -eq $env:COMPUTERNAME) -or ($TargetServer -eq ".")
$SourcePath = Resolve-Path $SourcePath -ErrorAction SilentlyContinue

Log "==================================================" "STEP"
Log "WEBCLIENT BUILD AND DEPLOY" "STEP"
Log "==================================================" "STEP"
Log "Source:     $SourcePath"
Log "Target:     $TargetServer`:$TargetPort -> $TargetPath"
Log "API URL:    $WebApiUrl"
Log "Local:      $isLocal"
Log "Skip Build: $SkipBuild"
Log ""

# ==============================================================
# STEP 1: Validate source
# ==============================================================
Log "STEP 1/6: Validating source project" "STEP"

if (-not (Test-Path $SourcePath)) {
    FailExit "Source path not found: $SourcePath"
}

$packageJson = Join-Path $SourcePath "package.json"
if (-not (Test-Path $packageJson)) {
    FailExit "package.json not found in $SourcePath. Is this a React project?"
}

# Detect build tool (Vite or CRA)
$pkgContent = Get-Content $packageJson -Raw | ConvertFrom-Json
$isVite = $pkgContent.devDependencies.PSObject.Properties.Name -contains "vite"
$buildOutputDir = if ($isVite) { "dist" } else { "build" }
Log "Detected: $(if ($isVite) { 'Vite' } else { 'Create React App' }) project" "OK"
Log "Build output: $buildOutputDir/" "OK"

# Check Node.js
$nodeVersion = node --version 2>$null
if (-not $nodeVersion) {
    FailExit "Node.js not found. Install from https://nodejs.org"
}
Log "Node.js: $nodeVersion" "OK"

$npmVersion = npm --version 2>$null
Log "npm: $npmVersion" "OK"

# ==============================================================
# STEP 2: Set environment and build
# ==============================================================
if (-not $SkipBuild) {
    Log "STEP 2/6: Building production artifacts" "STEP"

    Push-Location $SourcePath

    # Write .env.production with the API URL
    $envFile = if ($isVite) { ".env.production" } else { ".env.production.local" }
    $envKey = if ($isVite) { "VITE_API_BASE_URL" } else { "REACT_APP_API_BASE_URL" }

    $envContent = @"
# Generated by Publish-WebClient.ps1 at $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# Target: $TargetServer`:$TargetPort
$envKey=$WebApiUrl
"@
    Set-Content -Path (Join-Path $SourcePath $envFile) -Value $envContent -Encoding UTF8
    Log "Wrote $envFile`: $envKey=$WebApiUrl" "OK"

    # Install dependencies
    Log "Running npm ci (clean install)..."
    $npmResult = & npm ci 2>&1
    if ($LASTEXITCODE -ne 0) {
        Log "npm ci failed, trying npm install..." "WARN"
        $npmResult = & npm install 2>&1
        if ($LASTEXITCODE -ne 0) {
            Pop-Location
            FailExit "npm install failed: $($npmResult | Select-Object -Last 5)"
        }
    }
    Log "Dependencies installed" "OK"

    # Build
    Log "Running npm run build..."
    $buildResult = & npm run build 2>&1
    if ($LASTEXITCODE -ne 0) {
        Pop-Location
        $buildResult | Select-Object -Last 20 | ForEach-Object { Write-Host "    $_" -ForegroundColor DarkGray }
        FailExit "npm run build failed"
    }

    Pop-Location

    $distPath = Join-Path $SourcePath $buildOutputDir
    if (-not (Test-Path (Join-Path $distPath "index.html"))) {
        FailExit "Build succeeded but index.html not found in $distPath"
    }

    $fileCount = (Get-ChildItem $distPath -Recurse -File).Count
    $totalSize = [math]::Round((Get-ChildItem $distPath -Recurse -File | Measure-Object -Property Length -Sum).Sum / 1MB, 2)
    Log "Build complete: $fileCount files, ${totalSize} MB" "OK"
}
else {
    Log "STEP 2/6: Skipping build (using existing artifacts)" "SKIP"
    $distPath = Join-Path $SourcePath $buildOutputDir
    if (-not (Test-Path (Join-Path $distPath "index.html"))) {
        FailExit "No build artifacts found in $distPath. Run without -SkipBuild first."
    }
    Log "Using existing build in $distPath" "OK"
}

# ==============================================================
# STEP 3: Generate SPA web.config
# ==============================================================
Log "STEP 3/6: Generating IIS web.config" "STEP"

$webConfigContent = @'
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <rewrite>
      <rules>
        <rule name="SPA" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
            <add input="{REQUEST_URI}" pattern="^/api" negate="true" />
          </conditions>
          <action type="Rewrite" url="/" />
        </rule>
      </rules>
    </rewrite>
    <staticContent>
      <remove fileExtension=".json" />
      <mimeMap fileExtension=".json" mimeType="application/json" />
      <remove fileExtension=".woff" />
      <mimeMap fileExtension=".woff" mimeType="font/woff" />
      <remove fileExtension=".woff2" />
      <mimeMap fileExtension=".woff2" mimeType="font/woff2" />
      <remove fileExtension=".svg" />
      <mimeMap fileExtension=".svg" mimeType="image/svg+xml" />
      <remove fileExtension=".js" />
      <mimeMap fileExtension=".js" mimeType="application/javascript" />
      <remove fileExtension=".css" />
      <mimeMap fileExtension=".css" mimeType="text/css" />
    </staticContent>
    <httpCompression>
      <dynamicTypes>
        <add mimeType="application/javascript" enabled="true" />
        <add mimeType="text/css" enabled="true" />
      </dynamicTypes>
    </httpCompression>
    <httpProtocol>
      <customHeaders>
        <add name="X-Content-Type-Options" value="nosniff" />
        <add name="X-Frame-Options" value="SAMEORIGIN" />
      </customHeaders>
    </httpProtocol>
    <defaultDocument>
      <files><clear /><add value="index.html" /></files>
    </defaultDocument>
  </system.webServer>
</configuration>
'@

$webConfigPath = Join-Path $distPath "web.config"
Set-Content -Path $webConfigPath -Value $webConfigContent -Encoding UTF8
Log "Generated web.config with SPA routing + MIME types + compression" "OK"

# ==============================================================
# STEP 4: Copy artifacts to target
# ==============================================================
Log "STEP 4/6: Deploying to $TargetServer" "STEP"

if ($isLocal) {
    $deployPath = $TargetPath
}
else {
    $deployPath = "\\$TargetServer\c$\inetpub\TestControllerWebClient"
}

# Stop site before copying (if IIS is accessible)
if ($isLocal) {
    Import-Module WebAdministration -ErrorAction SilentlyContinue
    try {
        if (Test-Path "IIS:\Sites\$SiteName") {
            Stop-Website -Name $SiteName -ErrorAction SilentlyContinue
            Log "Stopped site: $SiteName" "OK"
        }
    }
    catch { Log "Could not stop site (may not exist yet)" "SKIP" }
}

# Clean and copy
if (Test-Path $deployPath) {
    Remove-Item $deployPath -Recurse -Force -ErrorAction SilentlyContinue
    Log "Cleaned old deployment" "OK"
}
New-Item -Path $deployPath -ItemType Directory -Force | Out-Null

$robocopyArgs = @($distPath, $deployPath, "/E", "/R:3", "/W:2", "/NFL", "/NDL", "/NJH", "/NJS", "/NP")
& robocopy @robocopyArgs | Out-Null
if ($LASTEXITCODE -gt 7) {
    FailExit "robocopy failed with exit code $LASTEXITCODE"
}

$deployedFiles = (Get-ChildItem $deployPath -Recurse -File).Count
Log "Deployed $deployedFiles files to $deployPath" "OK"

# Verify index.html exists at destination
if (-not (Test-Path (Join-Path $deployPath "index.html"))) {
    FailExit "index.html not found at $deployPath after copy"
}
Log "index.html verified at destination" "OK"

# ==============================================================
# STEP 5: Configure IIS (local only)
# ==============================================================
if ($isLocal) {
    Log "STEP 5/6: Configuring IIS" "STEP"

    $appcmd = "$env:windir\system32\inetsrv\appcmd.exe"

    # Ensure W3SVC is running
    $w3svc = Get-Service W3SVC -ErrorAction SilentlyContinue
    if (-not $w3svc -or $w3svc.Status -ne "Running") {
        Start-Service WAS -ErrorAction SilentlyContinue
        Start-Service W3SVC -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 2
    }

    # Clean up existing
    $existsSite = & $appcmd list site /name:"$SiteName" 2>$null
    if ($existsSite) {
        & $appcmd stop site /site.name:"$SiteName" 2>$null | Out-Null
        & $appcmd delete site /site.name:"$SiteName" 2>$null | Out-Null
        Log "Removed old site" "OK"
    }

    $existsPool = & $appcmd list apppool /name:"$PoolName" 2>$null
    if ($existsPool) {
        & $appcmd stop apppool /apppool.name:"$PoolName" 2>$null | Out-Null
        Start-Sleep -Seconds 1
        & $appcmd delete apppool /apppool.name:"$PoolName" 2>$null | Out-Null
        Log "Removed old pool" "OK"
    }

    # Unlock rewrite section
    & $appcmd unlock config -section:system.webServer/rewrite/rules 2>$null | Out-Null

    # Create fresh
    & $appcmd add apppool /name:"$PoolName" /managedRuntimeVersion:"" 2>$null | Out-Null
    Log "Created pool: $PoolName" "OK"

    & $appcmd add site /name:"$SiteName" /physicalPath:"$deployPath" /bindings:"http/*:${TargetPort}:" 2>$null | Out-Null
    & $appcmd set site /site.name:"$SiteName" /[path='/'].applicationPool:"$PoolName" 2>$null | Out-Null
    Log "Created site: $SiteName on port $TargetPort" "OK"

    # Permissions
    icacls $deployPath /grant "IIS AppPool\${PoolName}:(OI)(CI)RX" /T /Q 2>$null | Out-Null
    Log "Permissions set" "OK"

    # Firewall
    Remove-NetFirewallRule -DisplayName "TestController WebClient" -ErrorAction SilentlyContinue
    New-NetFirewallRule -DisplayName "TestController WebClient" -Direction Inbound -Protocol TCP -LocalPort $TargetPort -Action Allow -Profile Any | Out-Null
    Log "Firewall rule added: port $TargetPort" "OK"

    # Start
    & $appcmd start apppool /apppool.name:"$PoolName" 2>$null | Out-Null
    & $appcmd start site /site.name:"$SiteName" 2>$null | Out-Null
    Start-Sleep -Seconds 2
    Log "Site started" "OK"
}
else {
    Log "STEP 5/6: Remote deployment - IIS must be configured on $TargetServer" "WARN"
    Log "Run Deploy-TestController.ps1 on $TargetServer to configure IIS" "WARN"
    Log "Files are already at $deployPath" "OK"
}

# ==============================================================
# STEP 6: Validate
# ==============================================================
Log "STEP 6/6: Validating deployment" "STEP"

if ($isLocal) {
    $testUrl = "http://localhost:$TargetPort"
}
else {
    $testUrl = "http://${TargetServer}:$TargetPort"
}

for ($i = 1; $i -le 5; $i++) {
    try {
        $resp = Invoke-WebRequest -Uri $testUrl -UseBasicParsing -TimeoutSec 10 -ErrorAction Stop
        Log "WebClient responded: HTTP $($resp.StatusCode)" "OK"
        break
    }
    catch {
        if ($i -eq 5) {
            Log "WebClient test FAILED: $($_.Exception.Message)" "FAIL"
            Log "Check: netstat -ano | findstr :$TargetPort" "WARN"
        }
        else {
            Start-Sleep -Seconds 3
        }
    }
}

# ==============================================================
# Summary
# ==============================================================
$elapsed = (Get-Date) - $startTime
Log ""
Log "==================================================" "STEP"
Log "WebClient deployed in $($elapsed.ToString('mm\:ss'))" "STEP"
Log "==================================================" "STEP"
Log ""
Log "  URL:      $testUrl" "INFO"
Log "  API:      $WebApiUrl" "INFO"
Log "  Files:    $deployPath" "INFO"
if (-not $isLocal) {
    Log ""
    Log "  NEXT: Run on $TargetServer`:" "WARN"
    Log "  Deploy-TestController.ps1 -WebClientSource $deployPath ..." "WARN"
}
Log ""
