<#
    Pester 3.4 (the version that ships with Windows PowerShell 5.1) - "Should Be", not "Should -Be".

    The scripts under test run top to bottom, so dot-sourcing them would execute a cleanup. Instead
    the pure helpers are lifted out with the PowerShell AST and defined into this session.

    No real node is touched. The only test that writes to disk is the robocopy agreement block at the
    bottom, which builds and deletes its own sandbox under $env:TEMP.

    Run:  Invoke-Pester -Path .\deploy\Invoke-NodeCleanup.Tests.ps1
#>

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$cleanupScript  = Join-Path $here 'Invoke-NodeCleanup.ps1'
$manifestScript = Join-Path $here 'New-NodeManifest.ps1'
$fleetScript    = Join-Path $here 'Invoke-FleetDeployment.ps1'
$inventoryPath  = Join-Path $here 'fleet-inventory.json'

function Get-ScriptFunctionSource {
    param([string]$Path, [string[]]$Names)

    $ast = [System.Management.Automation.Language.Parser]::ParseFile($Path, [ref]$null, [ref]$null)
    $fns = $ast.FindAll({ $args[0] -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $true)

    $sb = New-Object System.Text.StringBuilder
    foreach ($n in $Names) {
        $f = @($fns | Where-Object { $_.Name -eq $n })
        if ($f.Count -eq 0) { throw "Function '$n' not found in $Path" }
        [void]$sb.AppendLine($f[0].Extent.Text)
    }
    return $sb.ToString()
}

# Dot-source at SCRIPT scope. Invoke-Expression inside the helper would define the functions in
# that helper's scope, and every test would then fail with CommandNotFoundException.
. ([scriptblock]::Create((Get-ScriptFunctionSource -Path $cleanupScript -Names @(
    'Get-TotalBytes', 'Test-PathInside', 'Test-IsPreserved', 'Get-JunkCategory',
    'Test-RecentCrashDump', 'Select-BackupSetsToDelete', 'Compare-NodeManifest',
    'Get-DottedValue', 'Set-JsonValuePreservingFormat'
))))

# Get-JunkCategory reads these two script-scope lists.
$script:ReportOnlyPatterns = @('*.jsonl')
$script:NeverTouchFolders  = @('runtimes')

$preserve = @(
    'appsettings.json', 'commandpolicy.json', '*.bak-*', 'WatchList.xml',
    'Prepare-Agent.bat', '*.bat', '*.cmd',
    'orchestrator.db', 'orchestrator.db-wal', 'orchestrator.db-shm',
    'impact-index.db', 'impact-index.db-wal', 'impact-index.db-shm',
    'impact-outcomes.db', 'impact-outcomes.db-wal', 'impact-outcomes.db-shm'
)

Describe 'Embedded protected lists match the inventory' {

    # fleet-inventory.json is the single source of truth. The embedded copies are GENERATED by
    # Sync-PreserveList.ps1 because the node has no repo. These tests assert the generated result
    # equals the inventory - not that some literal happens to appear in the file, which would pass
    # even if an entry were listed in an unrelated comment or a stale second array.
    function Get-EmbeddedArray {
        param([string]$Path, [string]$VariableName)
        $ast = [System.Management.Automation.Language.Parser]::ParseFile($Path, [ref]$null, [ref]$null)
        $assign = @($ast.FindAll({
            $args[0] -is [System.Management.Automation.Language.AssignmentStatementAst] -and
            $args[0].Left.Extent.Text -eq $VariableName
        }, $true)) | Select-Object -First 1
        if (-not $assign) { throw "Variable '$VariableName' not found in $Path" }
        $strings = $assign.Right.FindAll({
            $args[0] -is [System.Management.Automation.Language.StringConstantExpressionAst]
        }, $true)
        return @($strings | ForEach-Object { $_.Value })
    }

    It 'Invoke-NodeCleanup.ps1 preserveFiles equals the inventory, in order' {
        if (-not (Test-Path $inventoryPath)) { Set-TestInconclusive -Message 'fleet-inventory.json not present'; return }
        $inv = Get-Content $inventoryPath -Raw | ConvertFrom-Json
        $emb = Get-EmbeddedArray -Path $cleanupScript -VariableName '$script:FallbackPreserveFiles'
        ($emb -join '|') | Should Be ((@($inv.preserveFiles)) -join '|')
    }

    It 'Invoke-NodeCleanup.ps1 preserveFolders equals the inventory, in order' {
        if (-not (Test-Path $inventoryPath)) { Set-TestInconclusive -Message 'fleet-inventory.json not present'; return }
        $inv = Get-Content $inventoryPath -Raw | ConvertFrom-Json
        $emb = Get-EmbeddedArray -Path $cleanupScript -VariableName '$script:FallbackPreserveFolders'
        ($emb -join '|') | Should Be ((@($inv.preserveFolders)) -join '|')
    }

    It 'New-NodeManifest.ps1 preserveFiles equals the inventory, in order' {
        if (-not (Test-Path $inventoryPath)) { Set-TestInconclusive -Message 'fleet-inventory.json not present'; return }
        $inv = Get-Content $inventoryPath -Raw | ConvertFrom-Json
        $emb = Get-EmbeddedArray -Path $manifestScript -VariableName '$fallbackPreserveFiles'
        ($emb -join '|') | Should Be ((@($inv.preserveFiles)) -join '|')
    }

    It 'regenerating from the inventory is a no-op (Sync-PreserveList.ps1 -Check)' {
        $sync = Join-Path $here 'Sync-PreserveList.ps1'
        if (-not (Test-Path $sync)) { Set-TestInconclusive -Message 'Sync-PreserveList.ps1 not present'; return }
        & powershell -NoProfile -ExecutionPolicy Bypass -File $sync -Check | Out-Null
        $LASTEXITCODE | Should Be 0
    }

    It 'defines Test-IsPreserved identically in both scripts' {
        # Two copies exist because the node has no repo. If the bodies ever diverge, the cleanup and
        # the deploy can protect different files - which is the whole defect this block guards.
        # Get-ScriptFunctionSource throws when the function is absent, so reaching the compare is itself
        # an assertion that both scripts still define it.
        $a = (Get-ScriptFunctionSource -Path $cleanupScript -Names @('Test-IsPreserved')) -replace '\s+', ' '
        $b = (Get-ScriptFunctionSource -Path $fleetScript   -Names @('Test-IsPreserved')) -replace '\s+', ' '
        $a.Trim() | Should Be $b.Trim()
    }
}

Describe 'Get-TotalBytes' {

    It 'returns 0 for an empty collection instead of throwing' {
        # Measure-Object -Sum raises "Argument types do not match" on an empty set, and the script
        # runs with $ErrorActionPreference = Stop, so this once killed report generation on a node
        # that happened to be clean.
        Get-TotalBytes -Items @() | Should Be 0
        Get-TotalBytes -Items (New-Object System.Collections.Generic.List[object]) | Should Be 0
        Get-TotalBytes -Items $null | Should Be 0
    }

    It 'sums the named property' {
        $items = @(
            [pscustomobject]@{ Bytes = 100 },
            [pscustomobject]@{ Bytes = 250 }
        )
        Get-TotalBytes -Items $items | Should Be 350
    }

    It 'sums an alternative property' {
        $items = @(
            [pscustomobject]@{ Length = 10 },
            [pscustomobject]@{ Length = 32 }
        )
        Get-TotalBytes -Items $items -Property 'Length' | Should Be 42
    }
}

Describe 'Test-PathInside (the deletion boundary)' {

    It 'accepts a file under the root' {
        Test-PathInside -Candidate 'C:\TestAgentService\Logs\a.log' -Root 'C:\TestAgentService' | Should Be $true
    }

    It 'rejects a sibling folder with the same prefix' {
        # "C:\TestAgentServiceEVIL" starts with the root text but is a different folder.
        Test-PathInside -Candidate 'C:\TestAgentServiceEVIL\a.log' -Root 'C:\TestAgentService' | Should Be $false
    }

    It 'rejects traversal back out of the root' {
        Test-PathInside -Candidate 'C:\TestAgentService\..\Windows\x.dll' -Root 'C:\TestAgentService' | Should Be $false
    }

    It 'rejects the root itself' {
        Test-PathInside -Candidate 'C:\TestAgentService' -Root 'C:\TestAgentService' | Should Be $false
    }

    It 'tolerates a trailing separator on the root' {
        Test-PathInside -Candidate 'C:\TestAgentService\Logs\a.log' -Root 'C:\TestAgentService\' | Should Be $true
    }

    It 'rejects an unrelated path' {
        Test-PathInside -Candidate 'C:\Windows\System32\cmd.exe' -Root 'C:\TestAgentService' | Should Be $false
    }

    It 'rejects empty input' {
        Test-PathInside -Candidate '' -Root 'C:\TestAgentService' | Should Be $false
    }
}

Describe 'Test-IsPreserved' {

    It 'matches an exact name' {
        Test-IsPreserved -Name 'WatchList.xml' -Patterns $preserve | Should Be $true
    }

    It 'matches a wildcard pattern' {
        Test-IsPreserved -Name 'appsettings.json.bak-20260906-143800' -Patterns $preserve | Should Be $true
    }

    It 'protects a config backup taken by ANY tool, not just appsettings' {
        # commandpolicy.json.bak-20261002-221918 was written by Invoke-NodeCleanup.ps1 and deleted by
        # the fleet deploy's /MIR 20 seconds later, because the list only named appsettings backups.
        Test-IsPreserved -Name 'commandpolicy.json.bak-20261002-221918' -Patterns $preserve | Should Be $true
        Test-IsPreserved -Name 'WatchList.xml.bak-20261002-221918'      -Patterns $preserve | Should Be $true
    }

    It 'protects every .bat and .cmd' {
        Test-IsPreserved -Name 'Run-WASTests.bat' -Patterns $preserve | Should Be $true
        Test-IsPreserved -Name 'anything.cmd'     -Patterns $preserve | Should Be $true
    }

    It 'does not match a build artifact' {
        Test-IsPreserved -Name 'TestAgentGrpc.dll' -Patterns $preserve | Should Be $false
    }
}

Describe 'Get-JunkCategory (category-only deletion)' {

    $now = Get-Date '2026-10-03 12:00:00'

    It 'selects a log older than the retention window' {
        Get-JunkCategory -Name 'app_2026-09-01.log' -LastWriteTime $now.AddDays(-30) -Now $now `
            -RetentionDays 14 -PreservePatterns $preserve | Should Be 'OldLogs'
    }

    It 'keeps a log inside the retention window' {
        Get-JunkCategory -Name 'app_2026-10-02.log' -LastWriteTime $now.AddDays(-1) -Now $now `
            -RetentionDays 14 -PreservePatterns $preserve | Should BeNullOrEmpty
    }

    It 'selects a rotated log' {
        Get-JunkCategory -Name 'app.log.3' -LastWriteTime $now.AddDays(-60) -Now $now `
            -RetentionDays 14 -PreservePatterns $preserve | Should Be 'OldLogs'
    }

    It 'selects crash dumps and temp files' {
        Get-JunkCategory -Name 'crash_controller_1.dmp' -LastWriteTime $now.AddDays(-30) -Now $now `
            -RetentionDays 14 -PreservePatterns $preserve -DumpRetentionDays 7 | Should Be 'CrashDumps'
        Get-JunkCategory -Name 'x.tmp' -LastWriteTime $now -Now $now `
            -RetentionDays 14 -PreservePatterns $preserve -DumpRetentionDays 7 | Should Be 'TempFiles'
    }

    It 'keeps a crash dump newer than the dump retention window' {
        # A fresh dump is the evidence for whatever just crashed; deleting it destroys the diagnosis.
        Get-JunkCategory -Name 'crash_controller_1.dmp' -LastWriteTime $now.AddDays(-2) -Now $now `
            -RetentionDays 14 -PreservePatterns $preserve -DumpRetentionDays 7 | Should BeNullOrEmpty
    }

    It 'gates dumps on their own window, not the log window' {
        # 10 days old: past the 7 day dump window, but inside the 14 day log window.
        Get-JunkCategory -Name 'crash.dmp' -LastWriteTime $now.AddDays(-10) -Now $now `
            -RetentionDays 14 -PreservePatterns $preserve -DumpRetentionDays 7 | Should Be 'CrashDumps'
        Get-JunkCategory -Name 'crash.dmp' -LastWriteTime $now.AddDays(-10) -Now $now `
            -RetentionDays 14 -PreservePatterns $preserve -DumpRetentionDays 30 | Should BeNullOrEmpty
    }

    It 'deletes a temp file regardless of age' {
        Get-JunkCategory -Name 'fresh.tmp' -LastWriteTime $now -Now $now `
            -RetentionDays 14 -PreservePatterns $preserve -DumpRetentionDays 7 | Should Be 'TempFiles'
        Get-JunkCategory -Name 'old.tmp' -LastWriteTime $now.AddDays(-900) -Now $now `
            -RetentionDays 14 -PreservePatterns $preserve -DumpRetentionDays 7 | Should Be 'TempFiles'
    }

    It 'never selects audit jsonl, however old' {
        Get-JunkCategory -Name 'audit_2026-01-01.jsonl' -LastWriteTime $now.AddDays(-900) -Now $now `
            -RetentionDays 14 -PreservePatterns $preserve | Should BeNullOrEmpty
    }

    It 'never selects a preserved file, however old' {
        Get-JunkCategory -Name 'appsettings.json' -LastWriteTime $now.AddDays(-900) -Now $now `
            -RetentionDays 14 -PreservePatterns $preserve | Should BeNullOrEmpty
        Get-JunkCategory -Name 'Prepare-Agent.bat' -LastWriteTime $now.AddDays(-900) -Now $now `
            -RetentionDays 14 -PreservePatterns $preserve | Should BeNullOrEmpty
    }

    It 'never selects an ordinary binary' {
        Get-JunkCategory -Name 'TestAgentGrpc.dll' -LastWriteTime $now.AddDays(-900) -Now $now `
            -RetentionDays 14 -PreservePatterns $preserve | Should BeNullOrEmpty
    }
}

Describe 'Test-RecentCrashDump' {

    $now = Get-Date '2026-10-03 12:00:00'

    It 'flags a dump inside the window as evidence to keep' {
        Test-RecentCrashDump -Name 'crash.dmp' -LastWriteTime $now.AddDays(-2) -Now $now -DumpRetentionDays 7 | Should Be $true
    }

    It 'does not flag a dump past the window' {
        Test-RecentCrashDump -Name 'crash.dmp' -LastWriteTime $now.AddDays(-30) -Now $now -DumpRetentionDays 7 | Should Be $false
    }

    It 'ignores anything that is not a dump' {
        Test-RecentCrashDump -Name 'app.log' -LastWriteTime $now -Now $now -DumpRetentionDays 7 | Should Be $false
        Test-RecentCrashDump -Name 'x.tmp'   -LastWriteTime $now -Now $now -DumpRetentionDays 7 | Should Be $false
    }

    It 'treats a dump exactly at the boundary as keepable' {
        Test-RecentCrashDump -Name 'crash.dmp' -LastWriteTime $now.AddDays(-7) -Now $now -DumpRetentionDays 7 | Should Be $true
    }
}

Describe 'Select-BackupSetsToDelete (keep newest N)' {

    $sets = @('20260901-010101', '20260902-010101', '20260903-010101', '20260904-010101', '20260905-010101')

    It 'keeps the newest three and removes the rest' {
        $doomed = Select-BackupSetsToDelete -SetNames $sets -Keep 3
        $doomed.Count | Should Be 2
        ($doomed -contains '20260901-010101') | Should Be $true
        ($doomed -contains '20260902-010101') | Should Be $true
        ($doomed -contains '20260905-010101') | Should Be $false
    }

    It 'removes nothing when the count is at or below the limit' {
        (Select-BackupSetsToDelete -SetNames @('a', 'b') -Keep 3).Count | Should Be 0
        (Select-BackupSetsToDelete -SetNames $sets -Keep 5).Count | Should Be 0
    }

    It 'is a no-op on an empty or null list' {
        (Select-BackupSetsToDelete -SetNames @() -Keep 3).Count | Should Be 0
        (Select-BackupSetsToDelete -SetNames $null -Keep 3).Count | Should Be 0
    }

    It 'is idempotent - a second pass finds nothing left to remove' {
        $doomed = Select-BackupSetsToDelete -SetNames $sets -Keep 3
        $remaining = @($sets | Where-Object { $doomed -notcontains $_ })
        (Select-BackupSetsToDelete -SetNames $remaining -Keep 3).Count | Should Be 0
    }
}

Describe 'Compare-NodeManifest' {

    $manifest = @(
        [pscustomobject]@{ Path = 'TestAgentGrpc.dll'; Sha256 = 'AAA' },
        [pscustomobject]@{ Path = 'Core.dll';          Sha256 = 'BBB' },
        [pscustomobject]@{ Path = 'Gone.dll';          Sha256 = 'CCC' }
    )

    It 'reports Missing, Different and Extra' {
        $actual = @(
            [pscustomobject]@{ Path = 'TestAgentGrpc.dll'; Sha256 = 'AAA' },
            [pscustomobject]@{ Path = 'Core.dll';          Sha256 = 'ZZZ' },
            [pscustomobject]@{ Path = 'Stray.dll';         Sha256 = 'DDD' }
        )
        $r = Compare-NodeManifest -Manifest $manifest -Actual $actual -IgnorePatterns $preserve

        @($r | Where-Object { $_.Status -eq 'Missing'   -and $_.Path -eq 'Gone.dll' }).Count  | Should Be 1
        @($r | Where-Object { $_.Status -eq 'Different' -and $_.Path -eq 'Core.dll' }).Count  | Should Be 1
        @($r | Where-Object { $_.Status -eq 'Extra'     -and $_.Path -eq 'Stray.dll' }).Count | Should Be 1
        $r.Count | Should Be 3
    }

    It 'does not report host state as Extra' {
        # Without the ignore list every node would look wrong: these files legitimately differ.
        $actual = @(
            [pscustomobject]@{ Path = 'TestAgentGrpc.dll'; Sha256 = 'AAA' },
            [pscustomobject]@{ Path = 'Core.dll';          Sha256 = 'BBB' },
            [pscustomobject]@{ Path = 'Gone.dll';          Sha256 = 'CCC' },
            [pscustomobject]@{ Path = 'appsettings.json';  Sha256 = 'EEE' },
            [pscustomobject]@{ Path = 'WatchList.xml';     Sha256 = 'FFF' }
        )
        $r = Compare-NodeManifest -Manifest $manifest -Actual $actual -IgnorePatterns $preserve
        $r.Count | Should Be 0
    }

    It 'is case-insensitive on paths' {
        $actual = @(
            [pscustomobject]@{ Path = 'testagentgrpc.DLL'; Sha256 = 'AAA' },
            [pscustomobject]@{ Path = 'core.dll';          Sha256 = 'BBB' },
            [pscustomobject]@{ Path = 'GONE.dll';          Sha256 = 'CCC' }
        )
        (Compare-NodeManifest -Manifest $manifest -Actual $actual -IgnorePatterns $preserve).Count | Should Be 0
    }

    It 'reports nothing when the node matches exactly' {
        $actual = @(
            [pscustomobject]@{ Path = 'TestAgentGrpc.dll'; Sha256 = 'AAA' },
            [pscustomobject]@{ Path = 'Core.dll';          Sha256 = 'BBB' },
            [pscustomobject]@{ Path = 'Gone.dll';          Sha256 = 'CCC' }
        )
        (Compare-NodeManifest -Manifest $manifest -Actual $actual -IgnorePatterns $preserve).Count | Should Be 0
    }
}

Describe 'Config patch keeps formatting' {

    $json = @"
{
  // two-space indent, blank lines and key order must all survive
  "AgentSettings": {
    "AgentName": "jvgr2",
    "MaxExecutionTimeoutMinutes": 20160
  },

  "WindowsUpdate": {
    "Enabled": true,
    "ScanTimeoutSeconds": 180,
    "ScanPendingUpdates": true
  }
}
"@

    It 'replaces only the targeted value' {
        $out = Set-JsonValuePreservingFormat -Text $json -Path 'WindowsUpdate.ScanTimeoutSeconds' -NewValue 600
        $out.Contains('"ScanTimeoutSeconds": 600') | Should Be $true
        $out.Contains('"ScanTimeoutSeconds": 180') | Should Be $false
    }

    It 'leaves every other byte alone' {
        $out = Set-JsonValuePreservingFormat -Text $json -Path 'WindowsUpdate.ScanTimeoutSeconds' -NewValue 600
        $expected = $json.Replace('"ScanTimeoutSeconds": 180', '"ScanTimeoutSeconds": 600')
        $out | Should Be $expected
    }

    It 'scopes to the right object when a key name repeats' {
        $dup = @"
{
  "A": { "Shared": 1 },
  "B": { "Shared": 2 }
}
"@
        $out = Set-JsonValuePreservingFormat -Text $dup -Path 'B.Shared' -NewValue 99
        $out.Contains('"A": { "Shared": 1 }') | Should Be $true
        $out.Contains('"Shared": 99') | Should Be $true
    }

    It 'handles string and boolean values' {
        $out = Set-JsonValuePreservingFormat -Text $json -Path 'AgentSettings.AgentName' -NewValue 'jvgr7'
        $out.Contains('"AgentName": "jvgr7"') | Should Be $true

        $out2 = Set-JsonValuePreservingFormat -Text $json -Path 'WindowsUpdate.Enabled' -NewValue $false
        $out2.Contains('"Enabled": false') | Should Be $true
    }

    It 'returns null for a key that does not exist' {
        Set-JsonValuePreservingFormat -Text $json -Path 'WindowsUpdate.Nope' -NewValue 1 | Should BeNullOrEmpty
        Set-JsonValuePreservingFormat -Text $json -Path 'Missing.Branch' -NewValue 1 | Should BeNullOrEmpty
    }

    It 'is idempotent - re-applying the same value changes nothing' {
        $once  = Set-JsonValuePreservingFormat -Text $json  -Path 'WindowsUpdate.ScanTimeoutSeconds' -NewValue 600
        $twice = Set-JsonValuePreservingFormat -Text $once  -Path 'WindowsUpdate.ScanTimeoutSeconds' -NewValue 600
        $twice | Should Be $once
    }
}

Describe 'Get-DottedValue' {

    $obj = '{ "WindowsUpdate": { "ScanTimeoutSeconds": 180, "Enabled": true } }' | ConvertFrom-Json

    It 'reads a nested value' {
        Get-DottedValue -Root $obj -Path 'WindowsUpdate.ScanTimeoutSeconds' | Should Be 180
    }

    It 'returns null for a missing key or branch' {
        Get-DottedValue -Root $obj -Path 'WindowsUpdate.Nope' | Should BeNullOrEmpty
        Get-DottedValue -Root $obj -Path 'Nope.Nope'          | Should BeNullOrEmpty
    }
}

# ---------------------------------------------------------------------------
# Pass 0 and robocopy /XF must agree.
#
# This is the one place a sandbox on disk is unavoidable: the bug was that robocopy's real wildcard
# matching and Pass 0's exact-name matching disagreed, and only robocopy itself can prove the copy
# half. Everything happens under $env:TEMP and is removed in the last It of the block.
# ---------------------------------------------------------------------------
Describe 'Preserve list: Pass 0 agrees with robocopy /MIR' {

    . ([scriptblock]::Create((Get-ScriptFunctionSource -Path $fleetScript -Names @(
        'Test-IsPreserved', 'Get-UnprotectedState', 'Invoke-Robocopy'
    ))))

    # Get-UnprotectedState exempts only the deploy's own backup stamp, which the real script sets here.
    $stamp = '20261003-120000'

    $sandbox = Join-Path $env:TEMP ("fleet-preserve-" + [guid]::NewGuid().ToString('N').Substring(0, 8))
    $src = Join-Path $sandbox 'publish'
    $dst = Join-Path $sandbox 'node'
    New-Item -ItemType Directory -Path $src -Force | Out-Null
    New-Item -ItemType Directory -Path $dst -Force | Out-Null

    Set-Content -Path (Join-Path $src 'TestAgentGrpc.dll') -Value 'payload' -Encoding Ascii
    Set-Content -Path (Join-Path $dst 'TestAgentGrpc.dll') -Value 'payload' -Encoding Ascii

    # Node-only files. The .bak- pair is what the cleanup script used to leave in the install root.
    $backupLeaf = 'commandpolicy.json.bak-20261002-221918'
    Set-Content -Path (Join-Path $dst 'commandpolicy.json') -Value '{}' -Encoding Ascii
    Set-Content -Path (Join-Path $dst $backupLeaf)          -Value '{}' -Encoding Ascii
    Set-Content -Path (Join-Path $dst 'leftover.dll')       -Value 'x'  -Encoding Ascii

    It 'reports a third-party config backup as protected, not at risk' {
        $atRisk = @(Get-UnprotectedState -Remote $dst -Source $src -PreserveFiles $preserve -PreserveFolders @('Logs'))
        @($atRisk | Where-Object { $_.Path -eq $backupLeaf }).Count | Should Be 0
    }

    It 'still reports genuine orphans, so the check has not simply gone quiet' {
        $atRisk = @(Get-UnprotectedState -Remote $dst -Source $src -PreserveFiles $preserve -PreserveFolders @('Logs'))
        @($atRisk | Where-Object { $_.Path -eq 'leftover.dll' }).Count | Should Be 1
    }

    It 'exempts only THIS run stamp, not every .bak- file' {
        # A blanket '*.bak-*' skip used to sit in Get-UnprotectedState, so no backup from any other
        # tool could ever be reported. Proven here with a list that deliberately omits '*.bak-*':
        # protection must come from the preserve list, never from the check looking the other way.
        $noBakList = @($preserve | Where-Object { $_ -ne '*.bak-*' })
        Set-Content -Path (Join-Path $dst "other.json.bak-20250101-000000") -Value '{}' -Encoding Ascii
        Set-Content -Path (Join-Path $dst "appsettings.json.bak-$stamp")    -Value '{}' -Encoding Ascii

        $atRisk = @(Get-UnprotectedState -Remote $dst -Source $src -PreserveFiles $noBakList -PreserveFolders @('Logs'))
        @($atRisk | Where-Object { $_.Path -eq 'other.json.bak-20250101-000000' }).Count | Should Be 1
        @($atRisk | Where-Object { $_.Path -eq "appsettings.json.bak-$stamp" }).Count    | Should Be 0

        Remove-Item (Join-Path $dst "other.json.bak-20250101-000000") -Force
        Remove-Item (Join-Path $dst "appsettings.json.bak-$stamp") -Force
    }

    It 'survives robocopy /MIR with the same list handed to /XF' {
        Invoke-Robocopy -Source $src -Destination $dst -ExcludeFiles $preserve -ExcludeDirs @('Logs') -Mirror | Out-Null
        Test-Path (Join-Path $dst $backupLeaf)          | Should Be $true
        Test-Path (Join-Path $dst 'commandpolicy.json') | Should Be $true
    }

    It 'deleted the file Pass 0 warned about - the two agree in both directions' {
        Test-Path (Join-Path $dst 'leftover.dll') | Should Be $false
    }

    It 'cleans up the sandbox' {
        Remove-Item $sandbox -Recurse -Force -ErrorAction SilentlyContinue
        Test-Path $sandbox | Should Be $false
    }
}
