<#
.SYNOPSIS
    Regenerate the embedded preserve lists from deploy\fleet-inventory.json.

.DESCRIPTION
    fleet-inventory.json is the SINGLE SOURCE OF TRUTH for preserveFiles / preserveFolders.

    Invoke-NodeCleanup.ps1 and New-NodeManifest.ps1 each carry an embedded copy, because they
    run ON a node where the repository is not present. Those copies are generated by this
    script into the region delimited by:

        # <PreserveList:BEGIN>   ...   # <PreserveList:END>

    Anything outside the markers - including the explanatory comments - is left untouched.

    The inventory is also shipped next to Invoke-NodeCleanup.ps1 when it is published to a node,
    so the embedded copy is a genuine last-resort fallback rather than the live path.

.PARAMETER Check
    Do not write. Exit 1 if regenerating would change any target. Use this in CI or a pre-commit hook.

.EXAMPLE
    .\Sync-PreserveList.ps1
    Regenerate the embedded lists.

.EXAMPLE
    .\Sync-PreserveList.ps1 -Check
    Verify the embedded lists match the inventory; non-zero exit means drift.

.NOTES
    Compatibility : Windows PowerShell 5.1 and PowerShell 7+ (ASCII-only)
    Version       : 1.0  |  October 2026
#>
[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [string]$InventoryPath,
    [switch]$Check
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
if (-not $InventoryPath) { $InventoryPath = Join-Path $here 'fleet-inventory.json' }
if (-not (Test-Path -LiteralPath $InventoryPath)) { throw "Inventory not found: $InventoryPath" }

$begin = '# <PreserveList:BEGIN>'
$end   = '# <PreserveList:END>'

$inv             = Get-Content -LiteralPath $InventoryPath -Raw | ConvertFrom-Json
$preserveFiles   = @($inv.preserveFiles)
$preserveFolders = @($inv.preserveFolders)
if (-not $preserveFiles.Count)   { throw 'Inventory has no preserveFiles.' }
if (-not $preserveFolders.Count) { throw 'Inventory has no preserveFolders.' }

function Format-PsArray {
    # Multi-line array literal, one quoted entry per line.
    param([string]$Name, [string[]]$Items, [string]$Indent = '    ')
    $lines = @("$Name = @(")
    for ($i = 0; $i -lt $Items.Count; $i++) {
        $comma = if ($i -lt $Items.Count - 1) { ',' } else { '' }
        $lines += ("{0}'{1}'{2}" -f $Indent, $Items[$i].Replace("'", "''"), $comma)
    }
    $lines += ')'
    return ($lines -join "`n")
}

function Format-PsArrayInline {
    param([string]$Name, [string[]]$Items)
    $quoted = $Items | ForEach-Object { "'" + $_.Replace("'", "''") + "'" }
    return ("{0} = @({1})" -f $Name, ($quoted -join ', '))
}

# Each target declares the exact body its markers should contain.
$targets = @(
    @{
        Path = Join-Path $here 'Invoke-NodeCleanup.ps1'
        Body = @(
            (Format-PsArray      -Name '$script:FallbackPreserveFiles'   -Items $preserveFiles),
            (Format-PsArrayInline -Name '$script:FallbackPreserveFolders' -Items $preserveFolders)
        ) -join "`n"
    },
    @{
        Path = Join-Path $here 'New-NodeManifest.ps1'
        Body = (Format-PsArray -Name '$fallbackPreserveFiles' -Items $preserveFiles)
    }
)

$drift = 0
foreach ($t in $targets) {
    $path = $t.Path
    $name = Split-Path $path -Leaf
    if (-not (Test-Path -LiteralPath $path)) { Write-Host ("  {0,-28} MISSING" -f $name) -ForegroundColor Red; $drift++; continue }

    $original = [IO.File]::ReadAllText($path)
    $iB = $original.IndexOf($begin)
    $iE = $original.IndexOf($end)
    if ($iB -lt 0 -or $iE -lt 0 -or $iE -lt $iB) {
        Write-Host ("  {0,-28} markers not found - cannot generate" -f $name) -ForegroundColor Red
        $drift++
        continue
    }

    # Preserve the file's existing line ending rather than imposing one.
    $nl       = if ($original -match "`r`n") { "`r`n" } else { "`n" }
    $body     = ($t.Body -replace "`r?`n", $nl)
    $updated  = $original.Substring(0, $iB) + $begin + $nl + $body + $nl + $original.Substring($iE)

    if ($updated -ceq $original) {
        Write-Host ("  {0,-28} up to date" -f $name) -ForegroundColor Green
        continue
    }

    $drift++
    if ($Check) {
        Write-Host ("  {0,-28} DRIFT - embedded list does not match the inventory" -f $name) -ForegroundColor Red
        continue
    }
    if ($PSCmdlet.ShouldProcess($path, 'Regenerate preserve list')) {
        # UTF-8 without BOM, matching how these scripts are stored.
        [IO.File]::WriteAllText($path, $updated, (New-Object Text.UTF8Encoding($false)))
        Write-Host ("  {0,-28} regenerated" -f $name) -ForegroundColor Yellow
    }
}

Write-Host ''
Write-Host ("source: {0}" -f $InventoryPath) -ForegroundColor DarkGray
Write-Host ("files: {0}   folders: {1}" -f $preserveFiles.Count, $preserveFolders.Count) -ForegroundColor DarkGray

if ($Check -and $drift -gt 0) {
    Write-Host ''
    Write-Host "DRIFT DETECTED - run .\Sync-PreserveList.ps1 to regenerate." -ForegroundColor Red
    exit 1
}
exit 0
